src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_deb = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'evenements')]
    private Collection $user_event;

    #[ORM\ManyToOne(inversedBy: 'category')]
    private ?Category $category = null;

    #[ORM\Column(type: Types::BLOB)]
    private $picture = null;

    #[ORM\OneToMany(mappedBy: 'event_comment', targetEntity: Comments::class)]
    private Collection $comments;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'eventpkUser')]
    private ?User $pk_user = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'event_user')]
    private Collection $users;

    public function __construct()
    {
        $this->user_event = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDateDeb(): ?\DateTimeInterface
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTimeInterface $date_deb): static
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUserEvent(): Collection
    {
        return $this->user_event;
    }

    public function addUserEvent(User $userEvent): static
    {
        if (!$this->user_event->contains($userEvent)) {
            $this->user_event->add($userEvent);
        }

        return $this;
    }

    public function removeUserEvent(User $userEvent): static
    {
        $this->user_event->removeElement($userEvent);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function setPicture($picture = null): static
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setEventComment($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEventComment() === $this) {
                $comment->setEventComment(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPkUser(): ?User
    {
        return $this->pk_user;
    }

    public function setPkUser(?User $pk_user): static
    {
        $this->pk_user = $pk_user;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addEventUser($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeEventUser($this);
        }

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Evenement;
use App\Entity\User;
use StreamToFileTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class,[
                'label'=>'Nom de l\'évènement',
                'label_attr'=>['class'=>'form-control-label text-light'],
                'attr'=>['class'=> 'form-control']
            ])
            ->add('lieu',TextType::class,[
                'label'=>'Lieu de l\'évènement',
                'label_attr'=>['class'=>'form-control-label text-light'],
                'attr'=>['class'=> 'form-control']
            ])
            ->add('date_deb',DateTimeType::class,[
                'label'=>'Date de début de l\'évènement',
                'label_attr'=>['class'=>'form-control-label text-light'],
                'attr'=>['class'=> 'form-control'],
            ])
            ->add('date_fin',DateTimeType::class,[
                'label'=>'Date de fin de l\'évènement',
                'label_attr'=>['class'=>'form-control-label text-light'],
                'attr'=>['class'=> 'form-control']
            ])
            ->add('picture',FileType::class,[
                'label'=>'Image',
                'required'=>false,
                'data_class'=>null,
                'attr'=>['class'=> 'form-control'],
                'label_attr'=>['class'=>'form-control-label text-light'],
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                            'image/webp'
                        ],
                        'mimeTypesMessage' => 'Veuillez envoyer un fichier image valide',
                    ])
                ],
            ])
            ->add('category', EntityType::class, [
                'attr'=>['class'=> 'form-control'],
                'label'=>'Catégories',
                'label_attr'=>['class'=>'form-control-label text-light'],
                'class' => Category::class,
                'choice_label' => 'name',
            ])
        ;
        
        
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/evenement')]
class EvenementController extends AbstractController
{
    #[Route('/', name: 'app_evenement_index', methods: ['GET'])]
    public function index(EvenementRepository $evenementRepository,EntityManagerInterface $entityManager): Response
    {
        $events = $entityManager->getRepository(Evenement::class)->findAll();
        foreach($events as $ev){
            $ev->setPicture(base64_encode(stream_get_contents($ev->getPicture())));
        }
        return $this->render('evenement/index.html.twig', [
            'evenements' => $events,
        ]);
    }

    #[Route('/new', name: 'app_evenement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_show', methods: ['GET'])]
    public function show(Evenement $evenement,EntityManagerInterface $entityManager): Response
    {
        $events = $entityManager->getRepository(Evenement::class)->find($evenement);
    
        $events->setPicture(base64_encode(stream_get_contents($events->getPicture())));

        return $this->render('evenement/show.html.twig', [
            'evenement' => $events,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_evenement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $oldPictureContent = $evenement->getPicture();

        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);
        
        //dd(base64_encode(stream_get_contents($oldPictureContent->getPicture())));
        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $evenement->getPicture();
            if ($uploadedFile instanceof UploadedFile) {
                // Lire le contenu du nouveau fichier
                $fileContents = file_get_contents($uploadedFile->getPathname());
                $evenement->setPicture($fileContents);
            } elseif (empty($uploadedFile)) {
                
                $evenement->setPicture($oldPictureContent);
            }
            
            $entityManager->flush();
            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_delete', methods: ['POST'])]
    public function delete(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('app_evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/evenement/_form.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<div class="container card-body bg-primary p-5">
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.name) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.lieu) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.date_deb) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.date_fin) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.picture) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.category) }}
        </div>
    </div>
    <button class="btn btn-light text-dark mt-2">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}
</div>

    
{% endblock %}

templates/evenement/edit.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block content %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Admin - Listes des évènements{% endblock %}

{% block name_rubric %} Listes des évènements {% endblock %}

{% block content %}
        <table class="table table-striped">
    <thead class="thead">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Lieu</th>
            <th scope="col">Date début</th>
            <th scope="col">Date fin</th>
            <th scope="col">Picture</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.name }}</td>     
                <td>{{ evenement.lieu }}</td>
                <td>{{ evenement.dateDeb ? evenement.dateDeb|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    {% if evenement.picture is not null %}
                        <img src="data:image/png;base64,{{ evenement.picture }}" width=50 height=50 alt="Image">
                    {% else %}
                        Image non disponible
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('app_evenement_show', {'id': evenement.id}) }}" class="btn btn-info btn-sm">Show</a>
                    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}" class="btn btn-warning btn-sm">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Pas d'évènement disponible</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{{ path('app_evenement_new') }}" class="btn btn-primary">Créer un évènement</a>

{% endblock %}

templates/evenement/new.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Admin - Créer un évènement{% endblock %}

{% block content %}
    <h1>Création d'un évènement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('app_evenement_index') }}">retour à la liste</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Evenement{% endblock %}


    {% block name_rubric %}Editer un évènement {% endblock %}
    {% block content %}
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ evenement.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ evenement.name }}</td>
                </tr>
                <tr>
                    <th>Lieu</th>
                    <td>{{ evenement.lieu }}</td>
                </tr>
                <tr>
                    <th>Date_deb</th>
                    <td>{{ evenement.dateDeb ? evenement.dateDeb|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Date_fin</th>
                    <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Picture</th>
                    <td>
                        {% if evenement.picture is not null %}
                            <img src="data:image/png;base64,{{ evenement.picture }}" width=50 height=50 alt="Image">
                        {% else %}
                            Image non disponible
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('app_evenement_index') }}" class="btn btn-secondary mb-2">back to list</a>

        <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}" class="btn btn-primary mb-2">edit</a>

        {{ include('evenement/_delete_form.html.twig') }}
    {% endblock %}