src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type:'text')]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_comment = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $user_comment = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Evenement $event_comment = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $name): static
    {
        $this->description = $name;

        return $this;
    }

    public function getDateComment(): ?\DateTimeInterface
    {
        return $this->date_comment;
    }

    public function setDateComment(\DateTimeInterface $date_comment): static
    {
        $this->date_comment = $date_comment;

        return $this;
    }

    public function getUserComment(): ?User
    {
        return $this->user_comment;
    }

    public function setUserComment(?User $user_comment): static
    {
        $this->user_comment = $user_comment;

        return $this;
    }

    public function getEventComment(): ?Evenement
    {
        return $this->event_comment;
    }

    public function setEventComment(?Evenement $event_comment): static
    {
        $this->event_comment = $event_comment;

        return $this;
    }
}

src/Form/CommentsType.php
<?php

namespace App\Form;

use App\Entity\Comments;
use App\Entity\Evenement;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('description')
            ->add('date_comment')
            ->add('user_comment', EntityType::class, [
                'class' => User::class,
'choice_label' => 'id',
            ])
            ->add('event_comment', EntityType::class, [
                'class' => Evenement::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comments::class,
        ]);
    }
}

src/Controller/CommentsController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Form\CommentsType;
use App\Repository\CommentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comments')]
class CommentsController extends AbstractController
{
    #[Route('/', name: 'app_comments_index', methods: ['GET'])]
    public function index(CommentsRepository $commentsRepository): Response
    {
        return $this->render('comments/index.html.twig', [
            'comments' => $commentsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_comments_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $comment = new Comments();
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('app_comments_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comments/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comments_show', methods: ['GET'])]
    public function show(Comments $comment): Response
    {
        return $this->render('comments/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comments_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comments $comment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_comments_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comments/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comments_delete', methods: ['POST'])]
    public function delete(Request $request, Comments $comment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_comments_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comments/_delete_form.html.twig
<form method="post" action="{{ path('app_comments_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comments/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/comments/edit.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Edit Comments{% endblock %}

{% block content %}
    <h1>Edit Comments</h1>

    {{ include('comments/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_comments_index') }}">back to list</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}

templates/comments/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Comments index{% endblock %}

{% block content %}
    <h1>Comments index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Date_comment</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.description }}</td>
                <td>{{ comment.dateComment ? comment.dateComment|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_comments_show', {'id': comment.id}) }}" class="btn btn-info btn-sm">show</a>
                    <a href="{{ path('app_comments_edit', {'id': comment.id}) }}" class="btn btn-warning btn-sm">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_comments_new') }}">Create new</a>
{% endblock %}

templates/comments/new.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}New Comments{% endblock %}

{% block content %}
    <h1>Create new Comments</h1>

    {{ include('comments/_form.html.twig') }}

    <a href="{{ path('app_comments_index') }}">back to list</a>
{% endblock %}

templates/comments/show.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Comments{% endblock %}

{% block content %}
    <h1>Comments</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ comment.description }}</td>
            </tr>
            <tr>
                <th>Date_comment</th>
                <td>{{ comment.dateComment ? comment.dateComment|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_comments_index') }}">back to list</a>

    <a href="{{ path('app_comments_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}